[package]
name = "dom_reg"
version = "0.1.0"
authors = ["melbadry9 <me@melbadry9.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
requests = "0.0.30"
